### ISSUE TITLE
Support -c and --config flag with TOML based Config File

### ISSUE THREAD

**Issue by sdthaker** [mnajibi/tml#13]
Hi @mnajibi! I'd like to work on this feature to add support for parsing user input through a config file. I aim to implement this feature by using a TOML parsing library in Python. The implementation will address all the requirements mentioned in the lab and will only work to parse the flags which are currently supported by the codebase.

**Comment by mnajibi** [comment]
Hi @sdthaker ,

Thanks for offering to work on this feature! Feel free to go ahead with it. Your contributions are welcome!
