### ISSUE TITLE
Main function not returning when path is missing

### ISSUE THREAD

**Issue by omalk98** [mnajibi/tml#5]
At line 62

The following code checks for the existence of the path variable but only prints a message instead of returning. 
this issue is caught in the following if condition but should not be allowed to pass to that stage if the input is missing.

fix:
```python
if not args.path:
        parser.error("the following arguments are required: path")
        return
```

**Comment by mnajibi** [comment]
Below code has been added to fix the issue
```python
 if not args.path:
        parser.error("the following arguments are required: path")
        return
```
